### ISSUE TITLE
This script is not working

### ISSUE THREAD

**Issue by coonsmatthew** [meantheory/nvd#1]
When I run this script to pull in NVD vulnerabilities, it runs for around 1-2 minutes, creates the "data" folder, but then finishes without any error messages. When I navigate into the data directory, there are no CSV's in the directory however.

**Comment by meantheory** [comment]
Haven't used this script in a long time. Will look at it asap and see what's up.

**Comment by coonsmatthew** [comment]
Thank You!

**Comment by meantheory** [comment]
My first guess at a quick glance is that that this script has very many assumptions about the world and the world has changed. Went to NVD site (amazing how much that hasn't changed since I last looked at it years ago) and I did note they seem to be compressing all the files now which I do not believe they were doing when I wrote this - so that will need to be addressed.

I can fix it but it will probably have to be over the weekend. Will try to add some comments as not even I really remember what this thing does or why.

**Comment by meantheory** [comment]
Ok. I went a took a look at the script and tried to remember what it was I was doing. This was at the time a quick hack where I wanted to download the NVD feeds and turn them into CSV files for further processing. The idea was that I would run the script daily and process the changed CSV files. 

I fixed it to work with the way the NVD website is currently. I also fiddled with the way the caching works because whatever I was doing before was bizarre. Buyer beware - I have never used any of this in production. It is a great starting point if you need to download the feeds and do further processing on them but not much past that.

**Comment by meantheory** [comment]
I am curious to know what you would like this to do in the future in case I ever find myself working with NVD feeds again.

**Comment by coonsmatthew** [comment]
Sorry about the late reply. Everything's working great! I am actually using this to import the cvs output files into a MySQL database for vulnerability correlation.
